### ISSUE TITLE
Undefined symbols _ssl_ssl_*

### ISSUE THREAD

**Issue by greyfruit** [rainyt/zyheaps#25]
Hi! I really like this project, especially because its the only one project which example built successfully on my computer and running on my iPhone device 🎉 I appreciate your work because so far build native applications using `Heaps` is black box.

# Problem
I am stuck while trying to run my game project because of many errors related to `OpenSSL`. I think this errors appeared because of networking usage and I know that networking not supported yet on iOS and Android, but can you say do you working on it? Maybe you know what needs to be done for this?

# Screenshot
<img width="407" alt="Знімок екрана 2022-07-17 о 18 56 02" src="https://user-images.githubusercontent.com/22201424/179410759-f36dbdd8-76b9-4e97-8146-e208c2e02346.png">

**Comment by greyfruit** [comment]
I fixed all compile errors and now my game work in local network between host iMac and client iPhone! 🚀

- linked with precompiled universal `libuv.a` library
- added `ssl.c`, `uv.c`, `mbedtls/*.c` to compile sources phase
- updated system header search paths for libraries above

I think I can update iOS template and prepare PR later 👌

**Comment by rainyt** [comment]
Thank you. I will always try to complete other matters that have not been supported.  
I'm waiting for your IOS template pr.

**Comment by rainyt** [comment]
https://github.com/rainyt/zyheaps/commit/eb7ecef967aa36db69662084f44b458323563a5a
Fixed

**Comment by rainyt** [comment]
https://github.com/rainyt/zyheaps/commit/cab649f663e10cf0adb8d0a89a3001fc18b7546f
Fixed android ssl.

**Comment by greyfruit** [comment]
Thank you!
