### ISSUE TITLE
On testing html5 example I got this error.

### ISSUE THREAD

**Issue by oivoodoo** [rainyt/zyheaps#4]
Hi @rainyt 

Do you know the possible reason to have the error?

I am pretty new in haxe world :) and trying to use it once per year in summer time when I have a bit more time to be honest. And today I was following one of the PR where you posted your project and decided to give a try.

I would really appreciate if you see the possible error on building the project and give me some advice how to resolve it.

Thank you!

Haxe: 4.2.2
Heaps: git

```
/heaps/git/hxsl/Macros.hx:214: lines 214-219 : Too many arguments
/heaps/git/hxsl/Macros.hx:220: characters 16-30 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
/heaps/git/hxsl/Macros.hx:243: characters 6-23 : { type : haxe.macro.ComplexType, name : String, meta : Array<Unknown<0>>, isFinal : Null<Bool>, expr : { pos : hxsl.Position, expr : haxe.macro.Exp... has extra field meta
/heaps/git/hxsl/Macros.hx:243: characters 6-23 : ... For function argument 'vars'
/heaps/git/hxsl/Macros.hx:316: lines 316-322 : Object requires field ret
/heaps/git/hxsl/Macros.hx:316: lines 316-322 : ... For function argument 'f'
/heaps/git/hxsl/Macros.hx:328: lines 328-334 : Object requires field ret
/heaps/git/hxsl/Macros.hx:328: lines 328-334 : ... For function argument 'f'
/heaps/git/hxsl/Macros.hx:341: characters 21-24 : { type : haxe.macro.ComplexType, name : String, meta : Array<Unknown<0>>, isFinal : Null<Bool>, expr : { pos : haxe.macro.Position, expr : haxe.mac... has extra field meta
/heaps/git/hxsl/Macros.hx:341: characters 21-24 : ... For function argument 'vars'
/heaps/git/h3d/pass/Default.hx:3: characters 1-8 : Build failure
```

**Comment by rainyt** [comment]
Hi, I haven't encountered this problem, but you can try to change the haxe to version 4.2.5, If it still cannot be solved, you can provide samples to me.

**Comment by oivoodoo** [comment]
@rainyt going to give a try to delete everything and reinstall haxe, haxelib. 4.2.5 has the same stacktrace for me.I will update the issue if I resolve it by reinstalling everything. 

 thank you anyway!

**Comment by rainyt** [comment]
@oivoodoo  Hi, it's fix: https://github.com/rainyt/zyheaps/commit/961d9262545318509a751a6920c4d05175156666

**Comment by rainyt** [comment]
But your problem may be hxsl. What I fixed is res.

**Comment by oivoodoo** [comment]
Hi @rainyt . Everything works great. it was my problem. I had haxe 4.2.5 and old std folder that I set to use but actually, it should not be there. Cleaned up everything properly.

thank you!
